-- =========================================
-- DDC RDC — Cloudflare D1 Database Schema
-- =========================================

-- Table: Actualités / News Articles
CREATE TABLE IF NOT EXISTS news (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    excerpt     TEXT,
    content     TEXT,
    image_url   TEXT,
    date        TEXT NOT NULL,
    status      TEXT DEFAULT 'published' CHECK (status IN ('published', 'draft')),
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now'))
);

-- Table: Événements / Events
CREATE TABLE IF NOT EXISTS events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    description TEXT,
    image_url   TEXT,
    date        TEXT NOT NULL,
    location    TEXT,
    status      TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'past', 'draft')),
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now'))
);

-- Table: Publications / Think Tank
CREATE TABLE IF NOT EXISTS publications (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    excerpt     TEXT,
    type        TEXT DEFAULT 'RAPPORT' CHECK (type IN ('RAPPORT', 'ANALYSE', 'TRIBUNE')),
    date        TEXT NOT NULL,
    pages       INTEGER,
    url         TEXT,
    created_at  TEXT DEFAULT (datetime('now')),
    updated_at  TEXT DEFAULT (datetime('now'))
);

-- Table: Admin Users
CREATE TABLE IF NOT EXISTS admin_users (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    username    TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at  TEXT DEFAULT (datetime('now'))
);

-- =========================================
-- Default admin user (change password after first login!)
-- Password: "ddcrdc2025" — hashed with SHA-256
-- In production, use bcrypt or Argon2 via the Worker
-- =========================================
INSERT OR IGNORE INTO admin_users (username, password_hash)
VALUES ('admin', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8');
-- NOTE: The hash above is for "password". Replace this with a proper hash
-- generated by the Worker's /auth/setup endpoint on first deploy.

-- =========================================
-- Sample data (optional — remove in production)
-- =========================================

INSERT INTO news (title, excerpt, image_url, date, status) VALUES
('Conférence DDC — Vision Stratégique 2026', 'Session de réflexion stratégique sur le développement endogène avec les leaders de demain.', 'img/25-nov-2025/P77A9080.JPG', '2025-11-25', 'published'),
('Forum de la Jeunesse Congolaise', 'Mobilisation et échange entre jeunes leaders congolais pour bâtir un avenir meilleur.', 'img/sept-2025/P77A4745.jpg', '2025-09-15', 'published'),
('DDC Salongo — Action Communautaire', 'Journées de travaux communautaires et de sensibilisation citoyenne.', 'img/sept-oct-2024/Septembre - Octobre 2024/DDC Salongo (13).jpg', '2024-10-05', 'published');

INSERT INTO events (title, description, image_url, date, location, status) VALUES
('Conférence Annuelle DDC 2025', 'Grande conférence rassemblant tous les membres et sympathisants de la DDC RDC.', 'img/Juillet 2025/OFS_4237.JPG.jpg', '2025-07-20', 'Kinshasa, RDC', 'past'),
('Atelier de Formation Leadership', 'Session intensive de renforcement des capacités pour les cadres.', 'img/atelier-5-dec/_TOR6216.JPG', '2025-12-05', 'Kinshasa, RDC', 'past');

INSERT INTO publications (title, excerpt, type, date, pages) VALUES
('Vision 2030 : Stratégie de développement endogène pour la RDC', 'Feuille de route pour transformer l''économie congolaise par l''innovation locale.', 'RAPPORT', '2025-01-15', 12),
('L''entrepreneuriat jeune en RDC : Défis et opportunités', 'Étude approfondie sur l''écosystème entrepreneurial congolais.', 'ANALYSE', '2025-03-10', 8);
